### PR TITLE
fix: strip version prefix when loading contracts from disk (#2924)

### LINKED ISSUE #2924: WASM binary as WAT
Description

After auto-updating to Freenet v0.1.116 (built 2026-02-09T04:36:52Z), publishing any contract via fdev publish or fdev execute put fails with a WASM compilation error. The same contract code published successfully on prior versions.
Error

Error: Failed to receive response: client error: unhandled error: execution error: compile: 
WebAssembly translation error: Error when converting wat: input bytes aren't valid utf-8
Copy
The node appears to be trying to parse valid WASM binary as WAT (text format).
Environment

Freenet: 0.1.116 (f9416958c5bb)
fdev: 0.3.90
OS: Ubuntu 20.04 (aarch64/ARM)
Rust: cargo 1.93.0
Steps to Reproduce

Build a contract with fdev build (succeeds, produces valid WASM)
Publish: fdev publish --code build/freenet/contract_name contract --state initial_state.bin --webapp-archive webapp.tar.xz
Node rejects with the WAT utf-8 error
The packaged contract file contains a 32-byte hash prefix followed by valid WASM binary (\0asm magic at offset 0x22).

### PR DESCRIPTION
**Pull request by iduartgomez**
## Problem

After upgrading to v0.1.116, contract publishing failed with:
"Error when converting wat: input bytes aren't valid utf-8"

The node was trying to parse binary WASM as WAT (text format).

## Root Cause

Contracts are stored on disk with to_bytes_versioned() which adds
a version prefix. The fetch_contract() function was using
ContractContainer::try_from() which read raw file bytes including
the prefix.

When these bytes were passed to Module::new(), wasmer/wasmtime
auto-detection failed because:
- Binary WASM must start with magic bytes: 0x00 0x61 0x73 0x6d
- With the prefix, magic bytes were at offset 32, not offset 0
- Module::new() tried to parse as WAT text format
- Failed with "input bytes aren't valid utf-8"

## Solution

Replace ContractContainer::try_from() with
ContractCode::load_versioned_from_path() which properly strips
the version prefix before returning the WASM bytes.

This matches the existing pattern used in store_contract() (line 120).

## Testing

Added test_versioned_contract_loading_issue_2924 which:
1. Stores a contract with version prefix
2. Fetches it from disk (cache cleared)
3. Verifies WASM magic bytes are at offset 0
4. Verifies successful compilation without WAT parsing error

All existing contract_store tests pass.

https://claude.ai/code/session_012AJBRkaCkCwzN9PASiF1vW

Fixes #2924

### CODE REVIEW

**Comment by iduartgomez** [comment]
@claude do a PR review
